name: Docker Image Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file anaconda/.devcontainer/Dockerfile --tag my/anaconda:latest
